fifo:
	gcc fifoA.c -oA
	gcc fifoB.c -oB
proc:
	gcc procA.c -o procA
	gcc procB.c -o procB
sigaction:
	gcc sigaction.c -omain

sighandle:sighandle.c
	gcc sighandle.c -omain
demo1:
	gcc demo1.c -omain

sigsuspend:
	gcc suspend.c -omain

sigmask:
	gcc sigmask.c -omain
clean:
	rm -fr main
