demo3:
	gcc demo3.c -omain
demo2:
	gcc demo2.c -omain
pipedemo:
	gcc pipe.c -omain
sigqueue:
	gcc sigqueue.c -omain2
sigaction:
	gcc sigaction.c -omain

sighandle:sighandle.c
	gcc sighandle.c -omain
demo1:
	gcc demo1.c -omain

sigsuspend:
	gcc suspend.c -omain

sigmask:
	gcc sigmask.c -omain
clean:
	rm -fr main
