getch:getch.c
	gcc getch.c -omain -lcurses
demo3:
	gcc demo3.c -omain -lcurses
demo2:
	gcc demo2.c -omain -lcurses
cur_out:
	gcc cur_out.c -omain -lcurses
cur_init:cur_init.c
	gcc cur_init.c -omain -lcurses
map_write:map_write.c
	gcc map_write.c -omain
fstat:fstat.c
	gcc fstat.c -omain
demo1:demo1.c
	gcc demo1.c -omain
lseek:
	gcc lseek.c -omain
.PHONY:clean
clean:
	rm -f main *.o
