redir:
	gcc redir.c -omain
demo1:
	gcc demo1.c -omain
read:
	gcc read.c -omain
open:
	gcc open.c -omain
fd:
	gcc fd.c -omain
env:env.c
	gcc env.c -o main

getenv:
	gcc getenv.c -omain
.PHONY:clean

claen:
	rm -fr *.o main
