######################################################################
# Automatically generated by qmake (2.01a) Wed Feb 4 15:00:43 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
